default:
  image: docker
  services: ['docker:dind']
variables:
  DOCKER_DRIVER: overlay2
  PLATFORMS: linux/arm64/v8,linux/amd64
  REGISTRY_IMAGE: registry.etke.cc/etke.cc/base

base/build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --platform ${PLATFORMS} --push -t ${CI_REGISTRY_IMAGE}/build -t ${REGISTRY_IMAGE}/build -f Dockerfile.build .

base/app:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --platform ${PLATFORMS} --push -t ${CI_REGISTRY_IMAGE}/app -t ${REGISTRY_IMAGE}/app -f Dockerfile.app .
