stages:
  - build

build:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64 -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
